### ISSUE TITLE
Research Tab

### ISSUE THREAD

**Issue by makadenouk** [nia-edu-kh/nia-web#34]
Please translate the remaining English into Khmer.

**Comment by makadenouk** [comment]
Mr. KongSovanara please comment down the translation.

**Comment by jahbini** [comment]
@makadenouk -- when you wish the attention of a team member when you respond on Github, just type an '@' and a magic dropdown will appear with the team member's contact.  That member will get an e-mail pointing to your new comment.
So, @KongSovanara, please check the translation.

**Comment by makadenouk** [comment]
Ok!

Den
