### ISSUE TITLE
Facebook Page

### ISSUE THREAD

**Issue by jahbini** [nia-edu-kh/nia-web#4]
Create and link credentials for FB postings

**Comment by jahbini** [comment]
My investigations point to having both a FB Page, as well as a FB group.
The 'page' is publicly readable and is suitable for gaining the interest of a potential reader.  FB will let you push the page notices to more potential eyeballs, for a slight amount of money.
A 'group' is limited to some 5000 people and is the way to communicate with a specific audience (NIA students) -- we can run surveys, quizzes, or what-not.

Both the group and page require responsible administration and interaction to keep everybody sane, encourage good content, and keep the site ALIVE.

So, my question for youse guys: What group/page do we have, and what do we need?

**Comment by KongSovanara** [comment]
FB is popular now. Page and group are playing together. The importance is
sharing knowledge and information among others .
We should have
1. FB page
2. FB student affair group or Department group
3. Alumni group
The person responsible for this main task is also necessary.
So far most challenges resulted from the successor after the project.

Have a good weekend.
