### ISSUE TITLE
Translation on the faculty page

### ISSUE THREAD

**Issue by jahbini** [nia-edu-kh/nia-web#9]
Dear Mr.Jim
        I am using the equal sign to refer to "it is translated to" because it will be too long if i write the "it is translated to" every line. As for the word faculty, I am not sure how to translate it.
I will be sending you a lot of email which in each one will contain the translation to each pages. I hope you find this method a little bit convenient for you. If it isn't and you find it unpleasant to receive a lot of email, please let me know and I will sum up the whole translation into one or two emails. There is an error in spelling for the word engineer, I hope you don't forget to fix it.

DEPARTMENT = ដេប៉ាតឺម៉ង់
Department of Foundation Year = ដេប៉ាតឺម៉ង់ថ្នាក់ឆ្នាំសិក្សាមូលដ្ឋាន
Department of Basic Science and Environment = ដេប៉ាតឺម៉ង់វិទ្យាសាស្ត្រមូលដ្ឋាន និងបរិស្ថាន
Department of Agricultural Science = ដេប៉ាតឺម៉ង់វិទ្យាសាស្រ្តកសិកម្ម
Department of Forestry Science = ដេប៉ាតឺម៉ង់វិទ្យាសាស្ត្ររុក្ខកម្ម
Department of Fisheries Science = វិទ្យាសាស្រ្តជលផល
Department of Animal Science and Veterinary Medicine = ដេប៉ាតឺម៉ង់វិទ្យាសាស្រ្ត និងវិជ្ជសាស្រ្តសត្វ
Department of Horticulture = ដេប៉ាតឺម៉ង់សាកវប្បកម្ម
Department of Agricultural Extension and Rural Development = ដេប៉ាតឺម៉ង់ផ្សព្វផ្សាយកសិកម្ម និងអភិវឌ្ឍន៍ជនបទ
Department of Agricultural Economics = ដេប៉ាតឺម៉ង់សេដ្ឋកិច្ចកសិកម្ម
Department of Food processing = ដេប៉ាតឺម៉ង់កែច្នៃអាហារ
Department of Agricultural Engeneering (the word engineer is written incorrectly) = ដេប៉ាតឺម៉ង់វិស្វកម្មកសិកម្ម
Department of Information and Technology = ដេប៉ាតឺម៉ង់ព័ត៌មានវិទ្យា

 Best regards,
Ouk Makaden

**Comment by jahbini** [comment]
Has this been merged yet?

**Comment by makadenouk** [comment]
This particular translation has not yet been merged, but we've created the Department Tab and it states the same meaning so this issue is not needed.

**Comment by SamnangMeas** [comment]
I think everything  is fine no more thing to suggest.
